services:
  autoresdb:
    image: mysql:latest
    container_name: autoresdb
    environment:
      MYSQL_DATABASE: autoresdb
      MYSQL_PASSWORD: mario14y15.s
      MYSQL_ROOT_PASSWORD: mario14y15.
    ports:
      - "3307:3306"

  
  autoresbackend: 
    container_name: autoresbackend
    build: .   
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL= jdbc:mysql://autoresdb:3306/autoresdb?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mario14y15.
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - autoresdb
    restart: on-failure
    

       
