services:
  autoresdb:
    image: mysql:latest
    container_name: autoresdb
    environment:
      MYSQL_DATABASE: autoresdb
      MYSQL_PASSWORD: mario14y15.s
      MYSQL_ROOT_PASSWORD: mario14y15.
    ports:
      - "3307:3306"

  
  autoresbackend:
    build: .
    ports:
      - "8080:8080"
    container_name: autoresbackend
    depends_on:
      - autoresdb
    restart: on-failure
    

       
